global:
  projectName: bn-project
  appVersion: 0.0.1

keycloak:
  fullnameOverride: keycloak

  auth:
    adminUser: admin
    adminPassword: password

  proxy: edge

  service:
    type: LoadBalancer
    port: 8080
    targetPort: 8080
  
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: "nginx"
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: keycloak.local
        paths:
          - path: /
            pathType: Prefix
    tls: []

  postgresql:
    enabled: false
    host: "192.168.178.71" # Replace with the actual IP address of your Ubuntu machine
    database: "keycloak"
    user: "keycloak_user"
    password: "password"
    port: 5432 


  externalDatabase:
    host: "192.168.178.71" # Replace with the actual IP address of your Ubuntu machine
    database: "keycloak"
    user: "keycloak_user"
    password: "password"
    port: 5432
    existingSecret: ""

  extraEnvVars:
    - name: DB_VENDOR
      value: postgres
    - name: DB_ADDR
      value: "192.168.178.71" # Replace with the actual IP address of your Ubuntu machine
    - name: DB_DATABASE
      value: "keycloak"
    - name: DB_USER
      value: "keycloak_user"
    - name: DB_PASSWORD
      value: "password"

  extraVolumes:
    - name: keycloak-config-volume
      configMap:
        name: keycloak-config

  extraVolumeMounts:
    - name: keycloak-config-volume
      mountPath: /opt/keycloak/config/config.json
      subPath: config.json
