global:
  projectName: bn-project
  appVersion: 0.0.1

identityservice:

  image:
    repository: "ulihdocker/identityservice"
    pullPolicy: IfNotPresent
    tag: "latest"

  nameOverride: "identityservice"
  fullnameOverride: "identityservice"

  service:
    type: LoadBalancer
    port: 5044
    ports:
      - name: http
        port: 5044
        targetPort: 5044
        protocol: TCP
      - name: https
        port: 7283
        targetPort: 7283
        protocol: TCP   
    selector:
      app: identityservice

  proxy: edge

  aspnetCoreExtraEnvVars:
  - name: ASPNETCORE_URLS
    value: "https://+:7283;http://+:5044"
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  - name: ASPNETCORE_Kestrel__Certificates__Default__Path
    value: "/https/identityservice.pfx"
  - name: ASPNETCORE_Kestrel__Certificates__Default__Password
    valueFrom:
      secretKeyRef:
        name: identityservice-cert
        key: identityservice.pfx
  keycloakExtraEnvVars:
    - name: Keycloak__Authority
      value: http://keycloak.bn-auth.svc.cluster.local:8080/realms/bn-project
    - name: Keycloak__Host
      value: http://keycloak.bn-auth.svc.cluster.local:8080
    - name: Keycloak__Realm
      value: bn-project
    - name: Keycloak__ClientId
      value: bn-project-client
    - name: Keycloak__ClientSecret
      value: L7nsaqcDc1QrLSIrKvU0rEjUwgIP2pp0
    - name: Keycloak__AdminClientId
      value: config-cli
  connectionStringsExtraEnvVars:
    - name: ConnectionStrings__IdentityDbConnection
      value: Host=192.168.178.74;Port=5432;Database=bn_identity_dev;Username=bnproject_user;Password=L7n1P2pp0??13;

  volumes:
    - name: identityservice-cert
      secret:
        secretName: identityservice-cert

  volumeMounts:
    - name: identityservice-cert
      mountPath: "/https"
      readOnly: true



