global:
  projectName: bn-project
  appVersion: 0.0.2

keycloak:
  auth:
    adminUser: admin
    adminPassword: password
  proxy: edge
  service:
    type: ClusterIP
  database:
    vendor: postgres
    host: localhost
    port: 5432
    user: keycloak_user
    password: password
    database: keycloak