global:
  projectName: bn-project
  appVersion: 0.0.1

identityservice:

  image:
    repository: "ulihdocker/identityservice"
    pullPolicy: Always
    tag: "latest"

  nameOverride: "identityservice"
  fullnameOverride: "identityservice"

  service:
    type: ClusterIP
    port: 5044
    targetPort: 5044    
    selector:
      app: identityservice

  proxy: edge

  aspnetCoreExtraEnvVars:
  - name: ASPNETCORE_URLS
    value: "http://+:5044"
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  keycloakExtraEnvVars:
    - name: Keycloak__Authority
      value: http://keycloak.bn-auth.svc.cluster.local:8080/realms/bn-project
    - name: Keycloak__Host
      value: http://keycloak.bn-auth.svc.cluster.local:8080
    - name: Keycloak__Realm
      value: bn-project
    - name: Keycloak__ClientId
      value: bn-project-client
    - name: Keycloak__ClientSecret
      value: L7nsaqcDc1QrLSIrKvU0rEjUwgIP2pp0
    - name: Keycloak__AdminClientId
      value: config-cli
  connectionStringsExtraEnvVars:
    - name: ConnectionStrings__IdentityDbConnection
      value: Host=192.168.178.74;Port=5432;Database=bn_identity_dev;Username=bnproject_user;Password=L7n1P2pp0??13;



