global:
  projectName: bn-project
  appVersion: 0.0.1

keycloak:
  kind: deployment
  fullnameOverride: keycloak

  auth:
    adminUser: admin
    adminPassword: password

  proxy: edge

  service:
    type: LoadBalancer
    port: 8080
    targetPort: 8080 

  postgresql:
    enabled: false
    host: "192.168.178.74" # Replace with the actual IP address of your Ubuntu machine
    database: "keycloak"
    user: "keycloak_user"
    password: "password"
    port: 5432 

  externalDatabase:
    host: "192.168.178.74" # Replace with the actual IP address of your Ubuntu machine
    database: "keycloak"
    user: "keycloak_user"
    password: "password"
    port: 5432
    existingSecret: ""

  extraEnvVars:
    - name: DB_VENDOR
      value: postgres
    - name: DB_ADDR
      value: "192.168.178.74" # Replace with the actual IP address of your Ubuntu machine
    - name: DB_DATABASE
      value: "keycloak"
    - name: DB_USER
      value: "keycloak_user"
    - name: DB_PASSWORD
      value: "password"
    - name: KEYCLOAK_IMPORT
      value: /opt/jboss/keycloak/standalone/configuration/config-keycloak.json
  
  keycloakConfigCli:
    enabled: true
    configuration:
      config-keycloak.json: |
        {
            "id": "bn-project",
            "realm": "bn-project",
            "enabled": true,
            "roles": {
                "realm": [
                {
                    "name": "admin",
                    "description": "Administrator role with full access"
                },
                {
                    "name": "user",
                    "description": "User role with limited access"
                },
                {
                    "name": "guest",
                    "description": "Guest role with minimal access"
                }
                ]
            },
            "users": [
                {
                "username": "bn-admin",
                "email": "bn_admin@test.de",
                "firstName": "Uli",
                "lastName": "Herwig",
                "enabled": true,
                "emailVerified": true,
                "credentials": [
                    {
                    "type": "password",
                    "value": "Giwreh#1",
                    "temporary": false
                    }
                ],
                "realmRoles": [
                    "admin"
                ]
                },
                {
                "username": "bn-user",
                "email": "bn_user@test.de",
                "firstName": "John",
                "lastName": "Doe",
                "enabled": true,
                "emailVerified": true,
                "credentials": [
                    {
                    "type": "password",
                    "value": "Giwreh#1",
                    "temporary": false
                    }
                ],
                "realmRoles": [
                    "user"
                ]
                },
                {
                "username": "service-account-config-cli",
                "enabled": true,
                "serviceAccountClientId": "config-cli",
                "realmRoles": [
                    "uma_authorization",
                    "offline_access",
                    "admin"
                ],
                "clientRoles": {
                    "realm-management": [
                    "realm-admin"
                    ],
                    "account": [
                    "view-profile",
                    "manage-account"
                    ]
                },
                "notBefore": 0
                }
            ],
            "clients": [
                {
                "clientId": "bn-project-client",
                "enabled": true,
                "protocol": "openid-connect",
                "publicClient": false,
                "secret": "L7nsaqcDc1QrLSIrKvU0rEjUwgIP2pp0",
                "redirectUris": [
                    "*"
                ],
                "webOrigins": [
                    "*"
                ]
                },
                {
                "clientId": "config-cli",
                "enabled": true,
                "clientAuthenticatorType": "client-secret",
                "secret": "btbOPE9TGfTcCD3OmDP4DVvRa2jskaSt",
                "directAccessGrantsEnabled": false,
                "serviceAccountsEnabled": true,
                "publicClient": false,
                "protocol": "openid-connect"
                }
            ]
        }

kafka:
  fullnameOverride: kafka
  zookeeper:
    enabled: true
  replicaCount: 1
  configurationOverrides:
    server.properties: |
      listeners=PLAINTEXT://:9092
      advertised.listeners=PLAINTEXT://localhost:9092
      zookeeper.connect=zookeeper:2181
  metrics:
    kafka:
      enabled: true
  persistence:
    enabled: true
    size: 8Gi
    storageClass: ""

