global:
  projectName: bn-project
  appVersion: 0.0.1

keycloak:
  kind: deployment
  fullnameOverride: keycloak

  auth:
    adminUser: admin
    adminPassword: password

  proxy: edge

  service:
    type: LoadBalancer
    port: 8080
    targetPort: 8080 

  postgresql:
    enabled: false
    host: "192.168.178.71" # Replace with the actual IP address of your Ubuntu machine
    database: "keycloak"
    user: "keycloak_user"
    password: "password"
    port: 5432 

  externalDatabase:
    host: "192.168.178.71" # Replace with the actual IP address of your Ubuntu machine
    database: "keycloak"
    user: "keycloak_user"
    password: "password"
    port: 5432
    existingSecret: ""

  extraEnvVars:
    - name: DB_VENDOR
      value: postgres
    - name: DB_ADDR
      value: "192.168.178.71" # Replace with the actual IP address of your Ubuntu machine
    - name: DB_DATABASE
      value: "keycloak"
    - name: DB_USER
      value: "keycloak_user"
    - name: DB_PASSWORD
      value: "password"
    - name: KEYCLOAK_IMPORT
      value: /opt/jboss/keycloak/standalone/configuration/config-keycloak.json
  
  keycloakConfigCli:
    enabled: true
    configuration:
      config-keycloak.json: |
        {
            "id": "bn-project",
            "realm": "bn-project",
            "enabled": true,
            "roles": {
                "realm": [
                {
                    "name": "admin",
                    "description": "Administrator role with full access"
                },
                {
                    "name": "user",
                    "description": "User role with limited access"
                },
                {
                    "name": "guest",
                    "description": "Guest role with minimal access"
                }
                ]
            },
            "users": [
                {
                "username": "bn-admin",
                "email": "bn_admin@test.de",
                "firstName": "Uli",
                "lastName": "Herwig",
                "enabled": true,
                "emailVerified": true,
                "credentials": [
                    {
                    "type": "password",
                    "value": "Giwreh#1",
                    "temporary": false
                    }
                ],
                "realmRoles": [
                    "admin"
                ]
                },
                {
                "username": "bn-user",
                "email": "bn_user@test.de",
                "firstName": "John",
                "lastName": "Doe",
                "enabled": true,
                "emailVerified": true,
                "credentials": [
                    {
                    "type": "password",
                    "value": "Giwreh#1",
                    "temporary": false
                    }
                ],
                "realmRoles": [
                    "user"
                ]
                },
                {
                "username": "service-account-config-cli",
                "enabled": true,
                "serviceAccountClientId": "config-cli",
                "realmRoles": [
                    "uma_authorization",
                    "offline_access",
                    "admin"
                ],
                "clientRoles": {
                    "realm-management": [
                    "realm-admin"
                    ],
                    "account": [
                    "view-profile",
                    "manage-account"
                    ]
                },
                "notBefore": 0
                }
            ],
            "clients": [
                {
                "clientId": "bn-project-client",
                "enabled": true,
                "protocol": "openid-connect",
                "publicClient": false,
                "secret": "L7nsaqcDc1QrLSIrKvU0rEjUwgIP2pp0",
                "redirectUris": [
                    "*"
                ],
                "webOrigins": [
                    "*"
                ]
                },
                {
                "clientId": "config-cli",
                "enabled": true,
                "clientAuthenticatorType": "client-secret",
                "secret": "btbOPE9TGfTcCD3OmDP4DVvRa2jskaSt",
                "directAccessGrantsEnabled": false,
                "serviceAccountsEnabled": true,
                "publicClient": false,
                "protocol": "openid-connect"
                }
            ]
        }

zookeeper:
  replicaCount: 1
  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m

kafka:
  replicaCount: 1
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 1000m

identityService:
  replicaCount: 1
  aspnetCoreExtraEnvVars:
    - name: ASPNETCORE_URLS
      value: http://+:5044
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
  keycloakExtraEnvVars:
    - name: Keycloak__Authority
      value: http://keycloak:8080/realms/bn-project
    - name: Keycloak__Host
      value: http://keycloak:8080
    - name: Keycloak__Realm
      value: bn-project
    - name: Keycloak__ClientId
      value: bn-project-client
    - name: Keycloak__ClientSecret
      value: L7nsaqcDc1QrLSIrKvU0rEjUwgIP2pp0
    - name: Keycloak__AdminClientId
      value: config-cli
    - name: Keycloak__AdminClientSecret
      value: btbOPE9TGfTcCD3OmDP4DVvRa2jskaSt
  connectionStringsExtraEnvVars:
    - name: ConnectionStrings__IdentityDbConnection
      value: Host=192.168.178.7;Port=5432;Database=bn_identity_db;Username=bnproject_user;Password=L7n1P2pp0??13;




  
