# Default values for identityservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "ulihdocker/identityservice"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

serviceAccount:
  create: false

ingress:
  enabled: false

service:
  type: LoadBalancer
  loadBalancerIP: 192.168.178.105
  port: 5044
  targetPort: 5044    
  selector:
    app: identityservice

proxy: edge

aspnetCoreExtraEnvVars:
  - name: ASPNETCORE_URLS
    value: http://+:5044
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
keycloakExtraEnvVars:
  - name: Keycloak__Authority
    value: http://192.168.178.103:8080/realms/bn-project
  - name: Keycloak__Host
    value: http://192.168.178.103:8080
  - name: Keycloak__Realm
    value: bn-project
  - name: Keycloak__ClientId
    value: bn-project-client
  - name: Keycloak__ClientSecret
    value: L7nsaqcDc1QrLSIrKvU0rEjUwgIP2pp0
  - name: Keycloak__AdminClientId
    value: config-cli
  - name: Keycloak__AdminClientSecret
    value: btbOPE9TGfTcCD3OmDP4DVvRa2jskaSt
connectionStringsExtraEnvVars:
  - name: ConnectionStrings__IdentityDbConnection
    value: Host=192.168.178.74;Port=5432;Database=bn_identity_dev;Username=bnproject_user;Password=L7n1P2pp0??13;

# ingress:
#   enabled: true
#   className: "nginx"
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     kubernetes.io/tls-acme: "true"
#   hosts:
#     - host: identityservice.local
#       paths:
#         - path: /
#           pathType: ImplementationSpecific
#           backend:
#             service:
#               name: identityservice
#               port:
#                 number: 5044
 
#   tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
