# Default values for identityservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: false

ingress:
  enabled: false

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
