apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-keycloak
  labels:
    app: {{ .Release.Name }}-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-keycloak
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-keycloak
    spec:
      initContainers:
        - name: init-keycloak-config
          image: busybox
          command: ['sh', '-c', 'cp /config/config-keycloak.json /etc/keycloak/config-keycloak.json']
          volumeMounts:
            - name: config-volume
              mountPath: /config
      containers:
        - name: keycloak
          image: bitnami/keycloak:latest
          env:
            - name: KEYCLOAK_USER
              value: {{ .Values.keycloak.auth.adminUser }}
            - name: KEYCLOAK_PASSWORD
              value: {{ .Values.keycloak.auth.adminPassword }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/keycloak
      volumes:
        - name: config-volume
          configMap:
            name: keycloak-config
