# Default values for bn-client.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ulihdocker/bn-project-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: "bn-client"
fullnameOverride: "bn-client"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

serviceAccount:
  create: false

ingress:
  enabled: false

service:
  type: LoadBalancer
  loadBalancerIP: 192.168.178.102
  port: 3000
  targetPort: 3000
  selector:
    app: bn-client

proxy: edge

readinessProbe:
  httpGet:
    path: /
    port: 3001
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
